#! /bin/sh

bspc config border_width        1
bspc config window_gap         15

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc rule -a mplayer2 floating=on
bspc rule -a feh floating=on

panel &
nitrogen --restore

